version: "2.1"
services:
  static:
    build: ./nginx
    container_name: ${PROJECT_NAME}-static
    restart: always
    ports:
      - "${LOCALHOST_HTTP_PORT:-80}:80"
      - "${LOCALHOST_HTTPS_PORT:-443}:443"
    volumes:
      - ../.html:/usr/share/nginx/html
      - ../:/usr/share/nginx/html/wp-content/plugins/${PROJECT_NAME}
      - ./nginx/php54.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/includes:/etc/nginx/conf.d/includes
    depends_on:
      - app-php54
    expose:
      - "80"
      - "443"
    networks:
      default:
        aliases:
          - php54.local
    env_file: ../.env

  app-php54:
    build: ./php54
    container_name: ${PROJECT_NAME}-app-php54
    restart: always
    ports:
      - "${LOCALHOST_PHP54_PORT:-9054}:9000"
    volumes:
      - ../.html:/var/www/html
      - ../:/var/www/html/wp-content/plugins/${PROJECT_NAME}
    depends_on:
      - db-mysql57
    extra_hosts:
      - "remote_host:${XDEBUG_REMOTE_HOST}"
    networks:
      - default
    environment: 
      - WP_VERSION=${WP_VERSION}
      - WP_MULTISITE=${WP_MULTISITE}
      - WC_VERSION=${WC_VERSION}
    env_file:
      - wordpress.env
      - ../.env

  db-mysql57:
    build: ./mysql57
    container_name: ${PROJECT_NAME}-db-mysql57
    restart: always
    ports:
      - "${LOCALHOST_MYSQL57_PORT:-9017}:3306"
    volumes:
      - ../.data/mysql57:/var/lib/mysql
    networks:
      - default
    env_file: mysql.env

networks:
  default:
